// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL9BZIkV6Edw46hOJS32751sAYL2zSTiU',
    appId: '1:882203280456:web:4d129644246d5b62b6047d',
    messagingSenderId: '882203280456',
    projectId: 'cornea-yufoo1',
    authDomain: 'cornea-yufoo1.firebaseapp.com',
    storageBucket: 'cornea-yufoo1.appspot.com',
    measurementId: 'G-10SK07KJYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGXawx4m5dseUH6edvQckrnjtJGXMw8YA',
    appId: '1:882203280456:android:5b6ed89f94715b3eb6047d',
    messagingSenderId: '882203280456',
    projectId: 'cornea-yufoo1',
    storageBucket: 'cornea-yufoo1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB26-DB7AoN8NWZ4tHhrsdUYNgAgyEPO1g',
    appId: '1:882203280456:ios:635c3232ee7d54c9b6047d',
    messagingSenderId: '882203280456',
    projectId: 'cornea-yufoo1',
    storageBucket: 'cornea-yufoo1.appspot.com',
    iosClientId: '882203280456-sv0rdif5oqig1u6j7kph4iemjfhk27k9.apps.googleusercontent.com',
    iosBundleId: 'com.example.cornea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB26-DB7AoN8NWZ4tHhrsdUYNgAgyEPO1g',
    appId: '1:882203280456:ios:635c3232ee7d54c9b6047d',
    messagingSenderId: '882203280456',
    projectId: 'cornea-yufoo1',
    storageBucket: 'cornea-yufoo1.appspot.com',
    iosClientId: '882203280456-sv0rdif5oqig1u6j7kph4iemjfhk27k9.apps.googleusercontent.com',
    iosBundleId: 'com.example.cornea',
  );
}
